on:
  schedule:
    # runs every 5 minutes starting from minute 0 of every hour
    - cron:  '0/5 * * * *'

name: Update Schedule Data

jobs:
  render:
    name: Update Schedules
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install necessary packages
        run: |
          install.packages(c("dplyr", "lubridate", "glue", "magrittr"), dependencies = TRUE)
        shell: Rscript {0}
      - name: Run update script
        run: Rscript -e 'source("R/update_sched.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -am 'Updated Schedule' || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
