on:
  workflow_dispatch:

name: rebuild_participation

jobs:
  update:
    name: rebuild_participation
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
      NFLVERSE_REBUILD: true
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
           cache-version: 1
           extra-packages: |
            nflverse/nflreadr
            nflverse/ngsscrapR
            nflverse/nflverse-data
            ropensci/piggyback

      - name: Run participation update
        run: Rscript -e 'source("R/update_pbp_participation.R")'
